CREATE TABLE dbo.Developer(
DeveloperName NVARCHAR(32) NOT NULL PRIMARY KEY,
[Description] NVARCHAR(150) NOT NULL
)
CREATE TABLE dbo.Genre(
GenreName NVARCHAR(32) NOT NULL PRIMARY KEY,
[Description] NVARCHAR(150) NOT NULL
)
CREATE TABLE dbo.[User](
UserId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserName NVARCHAR(32) NOT NULL,
FirstName NVARCHAR(32) NOT NULL,
LastName NVARCHAR(32) NOT NULL,
DateJoined DATETIMEOFFSET NOT NULL,
LastActiveDate DATETIMEOFFSET NOT NULL,
IsRemoved INT NOT NULL
UNIQUE(UserName)
)
CREATE TABLE dbo.Game(
GameName NVARCHAR(32) NOT NULL PRIMARY KEY,
DeveloperName NVARCHAR(32) NOT NULL FOREIGN KEY
REFERENCES dbo.Developer(DeveloperName),
GenreName NVARCHAR(32) NOT NULL FOREIGN KEY
REFERENCES dbo.Genre(GenreName),
Price INT NOT NULL,
ReleaseDate DATETIMEOFFSET NOT NULL,
IsRemoved INT NOT NULL
)
CREATE TABLE dbo.[Library](
UserId INT NOT NULL FOREIGN KEY
REFERENCES dbo.[User](UserId),
GameName NVARCHAR(32) NOT NULL FOREIGN KEY
REFERENCES dbo.Game(GameName),
PurchasedDate DATETIMEOFFSET NOT NULL
PRIMARY KEY(UserId,GameName)
)
CREATE TABLE dbo.Review(
UserId INT NOT NULL FOREIGN KEY
REFERENCES dbo.[User](UserId),
GameName NVARCHAR(32) NOT NULL FOREIGN KEY
REFERENCES dbo.Game(GameName),
FiveStarScore INT NOT NULL CHECK(FiveStarScore>-1 AND FiveStarScore<6),
DateAdded DATETIMEOFFSET NOT NULL
PRIMARY KEY(UserId,GameName)
)
CREATE TABLE dbo.[Session](
SessionId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserId INT NOT NULL FOREIGN KEY
REFERENCES dbo.[Library](UserId),
GameName NVARCHAR(32) NOT NULL FOREIGN KEY
REFERENCES dbo.[Library](GameName),
SessionStartTime DATETIMEOFFSET NOT NULL,
SessionEndTime DATETIMEOFFSET NOT NULL
)