Use CIS560;
DROP TABLE IF EXISTS dbo.[Session]
DROP TABLE IF EXISTS dbo.[Library]
DROP TABLE IF EXISTS dbo.Review
DROP TABLE IF EXISTS dbo.Game
DROP TABLE IF EXISTS dbo.[User]
DROP TABLE IF EXISTS dbo.Developer
DROP TABLE IF EXISTS dbo.Genre

CREATE TABLE dbo.Developer(
DeveloperName NVARCHAR(32) NOT NULL PRIMARY KEY,
[Description] NVARCHAR(150) NOT NULL
)
CREATE TABLE dbo.Genre(
GenreName NVARCHAR(32) NOT NULL PRIMARY KEY,
[Description] NVARCHAR(150) NOT NULL
)
CREATE TABLE dbo.[User](
UserId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserName NVARCHAR(32) NOT NULL,
FirstName NVARCHAR(32) NOT NULL,
LastName NVARCHAR(32) NOT NULL,
DateJoined DATE NOT NULL,
LastActiveDate DATE NOT NULL,
IsRemoved INT NOT NULL CHECK(IsRemoved=1 OR IsRemoved = 0)
UNIQUE(UserName)
)
CREATE TABLE dbo.Game(
GameName NVARCHAR(32) NOT NULL PRIMARY KEY,
DeveloperName NVARCHAR(32) NOT NULL FOREIGN KEY
REFERENCES dbo.Developer(DeveloperName),
GenreName NVARCHAR(32) NOT NULL FOREIGN KEY
REFERENCES dbo.Genre(GenreName),
Price DECIMAL(10,2) NOT NULL,
ReleaseDate DATE NOT NULL,
IsRemoved INT NOT NULL CHECK(IsRemoved=1 OR IsRemoved = 0)
)
CREATE TABLE dbo.[Library](
UserId INT NOT NULL FOREIGN KEY
REFERENCES dbo.[User](UserId),
GameName NVARCHAR(32) NOT NULL FOREIGN KEY
REFERENCES dbo.Game(GameName),
PurchasedDate DATE NOT NULL
PRIMARY KEY(UserId,GameName)
)
CREATE TABLE dbo.Review(
UserId INT NOT NULL FOREIGN KEY
REFERENCES dbo.[User](UserId),
GameName NVARCHAR(32) NOT NULL FOREIGN KEY
REFERENCES dbo.Game(GameName),
[Description] NVARCHAR(150) NOT NULL,
FiveStarScore INT NOT NULL CHECK(FiveStarScore>-1 AND FiveStarScore<6),
DateAdded DATE NOT NULL
PRIMARY KEY(UserId,GameName)
)
CREATE TABLE dbo.[Session](
SessionId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserId INT NOT NULL,
GameName NVARCHAR(32) NOT NULL, 
SessionStartTime DATETIMEOFFSET NOT NULL,
SessionEndTime DATETIMEOFFSET NOT NULL,
CONSTRAINT Lib
FOREIGN KEY (UserId,GameName)
	REFERENCES dbo.[Library](UserId,GameName)
)
